UPDATE attendance 
SET Hours = TIMESTAMPDIFF(hour, DATE_FORMAT(DATE_ADD(TimeLogIn_AM, INTERVAL 30 MINUTE),'%Y-%m-%d %H:00:00'), 
DATE_FORMAT(DATE_ADD(TimeLogOut_AM, INTERVAL 30 MINUTE),'%Y-%m-%d %H:00:00'));